### ISSUE TITLE
2-3 서버와 클라이언트 혹은 경로상 라우터의 mtu가 다른 경우는 어떻게 동작할까?

### ISSUE THREAD

**Issue by pjtae0328** [bc-back-end-study/success-failure-network#19]
이전에 공부한 내용이지만 같이 공부하면 좋은 내용 같아서 질문 올렸습니다.

**Comment by pjtae0328** [comment]
ip 단편화가 발생한다.

**Comment by lsj8367** [comment]
헷갈리니 계층별 부르는 데이터 단위를 이미지 퍼와봅니다!
![image](https://user-images.githubusercontent.com/74235102/208278613-e4e0aaae-ce7e-40c6-9e6a-3db571505763.png)

출처 - https://velog.io/@hidaehyunlee/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%84%B8%EA%B7%B8%EB%A8%BC%ED%8A%B8-%ED%8C%A8%ED%82%B7-%ED%97%B7%EA%B0%88%EB%A6%B4-%EB%95%90-PDU%EB%A5%BC-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90
