### ISSUE TITLE
2-3 복수의 ACK 통지가 연속해서 일어난 경우가 어떤 상황에서 발생할까?

### ISSUE THREAD

**Issue by server-gaebal** [bc-back-end-study/success-failure-network#20]

**Comment by server-gaebal** [comment]
추가로 ACK 번호 통지가 연속적으로 일어나면 도중의 것은 생략되고 마지막 것만 보내는데, 패킷의 도착 순서가 꼬일 경우, 어떤식으로 수신측에서 보장하는지?

**Comment by pjtae0328** [comment]
1. 책에서 설명하는 복수의 ACK 통지라는 표현은 패킷을 여러개 수신 한 경우 각각 생성되는 ACK 번호를 의미 하는 것으로 보이며 프로세스가 수신 버퍼를 읽고 난 후에 남은 윈도우 사이즈 + 마지막 ACK 번호만을 응답하게 된다.

**Comment by server-gaebal** [comment]
파이프 라인 오류 회복의 기본적인 접근법인 GBN(Go-Back-N)과 SR(Selective-Repeat)의 시각화 - https://www2.tkn.tu-berlin.de/teaching/rn/animations/gbn_sr/

**Comment by lsj8367** [comment]
https://github.com/bc-back-end-study/success-failure-network/wiki/%EC%9C%88%EB%8F%84%EC%9A%B0-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98
