### ISSUE TITLE
2-5 수신처가 기록되어있는 표가 관리되는 방법은?

### ISSUE THREAD

**Issue by JoYuKang** [bc-back-end-study/success-failure-network#21]
중계 장치에 도착한 패킷의 헤더를 조사하여 패킷의 목적지를 판단하는 정보가 있는 표를 관리하는 방법이 궁금합니다.

**Comment by lsj8367** [comment]
@JoYuKang description에 질문의 요약본을 정리해도 좋을것 같아요

**Comment by pjtae0328** [comment]
![image](https://user-images.githubusercontent.com/83262217/211176792-5291d0d6-e4bf-45a7-a7c6-120e011773ae.png)
