### ISSUE TITLE
라우터와 허브 동작 차이

### ISSUE THREAD

**Issue by 0seony** [bc-back-end-study/success-failure-network#22]
* 함께 정리하고자 올린 이슈

**Comment by prk4224** [comment]
208~9p에 대한 내용이 나와있어, 다음주 story 2 를 보고 정리하기 !

**Comment by lsj8367** [comment]
리피터 허브에는 MAC주소를 관리하는게 존재하지 않음.
스위칭 허브는 MAC주소 테이블이 존재하기 때문에 일종의 캐시처리를 하게 되기 때문에 리피터 허브의 **브로드캐스트** 된 패킷을 동일한 MAC주소에 여러번 보내는 경우 패킷을 폐기할 수 있다.

스위칭 허브와 라우터의 차이
- 스위칭 허브는 MAC주소를 기반으로 패킷 전송한다.
- 라우터는 IP주소를 기반으로 다른 네트워크에 패킷을 전송한다.

![스크린샷 2023-02-05 오전 10 31 17](https://user-images.githubusercontent.com/74235102/216797054-b4049c34-cba6-40a5-be3e-867d76c54339.png)
이미지 출처 - https://minkwon4.tistory.com/288

**Comment by pjtae0328** [comment]
L1계층의 리피터 허브는 맥주소가 존재하지 않으며 들어온 신호를 해당 포트를 제외한 모든 포트로 중계한다.
L2계층의 스위칭 허브는 맥주소가 존재하지 않으며 들어온 신호의  MAC 헤더를 확인하여 수신처로 그대로 돌아가는 패킷의 경우 폐기하고 그렇지 않으면 MAC주소 테이블을 확인하여 어떤 포트로 보내야 할지 판단 후 릴레이한다. 만약 테이블에 존재하지 않는다면 플루딩(보낸 포트를 제외한 모든 포트로 전송)한다.

L3계층의 라우터는 맥주소가 존재하며 해당 장비의 맥주소로 도착한 패킷인지 MAC헤더를 확인 후 아니라면 폐기하고 맞다면 IP헤더를 확인하여 라우팅 테이블을 통해 도착지점으로 가기 위한 다음 경로의 ip주소를 찾고 맥테이블을 통해 다음 도착지의 ip주소 맥주소를 확인하고 새로운 MAC헤더를 만들어서 전송한다.
다만 MAC테이블에 다음 도착지 ip의 MAC이 없다면 ARP를 통해 맥 주소를 회득한다.

**Comment by prk4224** [comment]
라우터랑 스위칭 허브의 동작 자체는 해당 목적지로 검색해서 보내는 건 비슷하지만 
내부적으로 허브는 MAC 테이블만 조사해서 해당 MAC에 해당하는 포트로만 보내는 역할을 하고 
라우터는 패킷 조사,IP 조사, 라우팅 등 많은 역할은 한다.
