### ISSUE TITLE
2-2 TCP 헤더의 '사용하지 않음 필드'는 왜 있는걸까?

### ISSUE THREAD

**Issue by server-gaebal** [bc-back-end-study/success-failure-network#3]

**Comment by lsj8367** [comment]
헤더정보 관련 정리
출처 - https://evan-moon.github.io/2019/11/10/header-of-tcp/

**Comment by 0seony** [comment]
TCP헤더의 '사용하지 않음' 필드는 미래를 위해 만들어 놓은 예약된 필드로, 값은 항상 0으로 설정되어 있어야 한다.
이 필드는 총 헤더 크기를 4 바이트의 배수로 정렬하는 목적으로 사용된다.

**Comment by lsj8367** [comment]
원래는 `사용하지 않음` 필드는 6bit로 유지되었었는데, NS, CWR, ECE 플래그 비트가 추가되면서 3bit로 변경되었다.
NS: ECN-nonce (은폐 보호, RFC3540)
CWR: Congestion Window Reduced (혼잡 윈도우 축소, RFC3168)
ECE: ECN-Echo (RFC3168)

**Comment by prk4224** [comment]
#### Header 크기가 4 byte 배수로 정렬되는 이유

https://www.quora.com/What-is-the-purpose-of-4-bit-header-length-in-IPv4-packet-format
